import turtle

iteration = int(input("Enter number of iterations: "))
Iteration = iteration
if iteration < 1:
    print("Invalid number of iterations")
    exit()

l = 512 / (2 ** iteration)


turtle.penup()
turtle.goto(-256, 256 - l)
turtle.speed(10)

def base():
    turtle.pendown()
    turtle.forward(l)
    turtle.right(90)
    turtle.forward(l)
    turtle.right(90)
    turtle.forward(l)
    turtle.penup()

def iterate(iteration):
    v = 0
    if iteration == 1:
        base()
    elif iteration == 2:
        iterate(iteration - 1)
        turtle.pendown()
        turtle.left(90)
        turtle.forward(l)
        turtle.penup()
        turtle.left(90)
        iterate(iteration - 1)
        turtle.forward(256 / (2 ** (Iteration - iteration)))
        turtle.right(90)
        iterate(iteration - 1)
        turtle.pendown()
        turtle.left(90)
        turtle.forward(l)
        turtle.penup()
        turtle.left(90)
        turtle.forward(512 / (2 ** (Iteration - iteration)) - l)
        turtle.pendown()
        turtle.left(90)
        turtle.forward(l)
        turtle.penup()
        turtle.left(90)
        iterate(iteration - 1)
    elif iteration % 2 == 1:
        iterate(iteration - 1)
        turtle.left(180)
        turtle.forward(256 / (2 ** (Iteration - iteration)) - l)
        turtle.pendown()
        turtle.forward(l)
        turtle.left(90)
        turtle.penup()
        turtle.forward(256 / (2 ** (Iteration - iteration)) - 2 * l)
        iterate(iteration - 1)
        turtle.left(180)
        turtle.forward(256 / (2 ** (Iteration - iteration)) - l)
        turtle.right(90)
        turtle.pendown()
        turtle.forward(l)
        turtle.penup()
        turtle.forward(256 / (2 ** (Iteration - iteration)) - l)
        turtle.right(90)
        turtle.forward(256 / (2 ** (Iteration - iteration)) - 2 * l)
        iterate(iteration - 1)
        turtle.left(180)
        turtle.forward(256 / (2 ** (Iteration - iteration)))
        turtle.left(90)
        turtle.forward(512 / (2 ** (Iteration - iteration)) - l)
        turtle.left(90)
        turtle.pendown()
        turtle.forward(l)
        turtle.left(90)
        turtle.penup()
        turtle.forward(256 / (2 ** (Iteration - iteration)) - 2 * l)
        iterate(iteration - 1)
        turtle.left(180)
        turtle.forward(256 / (2 ** (Iteration - iteration)) - l)
    else:
        iterate(iteration - 1)
        turtle.left(90)
        turtle.forward(256 / (2 ** (Iteration - iteration)) - l)
        turtle.pendown()
        turtle.forward(l)
        turtle.left(90)
        turtle.penup()
        turtle.forward(256 / (2 ** (Iteration - iteration)) - 2 * l)
        iterate(iteration - 1)
        turtle.left(90)
        turtle.forward(256 / (2 ** (Iteration - iteration)) - l)
        turtle.right(90)
        turtle.pendown()
        turtle.forward(l)
        turtle.penup()
        turtle.forward(256 / (2 ** (Iteration - iteration)) - l)
        turtle.right(90)
        turtle.forward(256 / (2 ** (Iteration - iteration)) - 2 * l)
        iterate(iteration - 1)
        turtle.left(90)
        turtle.forward(256 / (2 ** (Iteration - iteration)))
        turtle.left(90)
        turtle.forward(512 / (2 ** (Iteration - iteration)) - l)
        turtle.left(90)
        turtle.pendown()
        turtle.forward(l)
        turtle.left(90)
        turtle.penup()
        turtle.forward(256 / (2 ** (Iteration - iteration)) - 2 * l)
        iterate(iteration - 1)
        turtle.left(90)
        turtle.forward(256 / (2 ** (Iteration - iteration)) - l)
        turtle.right(90)





turtle.setheading(90)
iterate(iteration)
turtle.hideturtle()
turtle.done()